[package]
name = "compile-fail"
version = "0.1.0"
authors = ["jean <jean.dumoulin@insa-rennes.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="=0.2.61"
